### ISSUE TITLE
TypeError: sharp.block is not a function

### ISSUE THREAD

**Issue by mzaidsqbt** [Ilyes-El-Majouti/pdftopic#11]
Hi there I have installed the latest version of pdf-topic. My node version is 16.20.0 and I am encountering this error - 
TypeError: sharp.block is not a function

this is the version of sharp installed with the package.

npm list sharp

src@1.0.0 /Users/mohdzaidmultani/Desktop/Projects/contract-backend/src
└─┬ pdftopic@1.0.6-alpha
  └── sharp@0.31.3
  
  Please help!

**Comment by TelmoFerreira** [comment]
Same error here, any solution?

**Comment by MykhailoMatiiasevychKlarna** [comment]
Same error. Works with `1.0.4-alpha`

**Comment by Ilyes-El-Majouti** [comment]
Hello, excuse me, I was on vacation, I'll sort it out during the day, sorry again.

**Comment by Ilyes-El-Majouti** [comment]
Hello, an update has been made to correct this problem.
